templates:
  - '/config/*.tmpl'

route:
  receiver: telegram
  group_wait: 5s
  group_interval: 30s
  repeat_interval: 30m

receivers:
  - name: telegram
    telegram_configs:
      - bot_token: TOKEN
        chat_id: CHAT_ID
        message: '{{ template "telegram.message" . }}'
