apiVersion: 1

datasources:
  - name: victoriametrics
    type: prometheus
    access: proxy
    orgId: 1
    uid: DS_VM_01
    url: http://victoriametrics:8428
    basicAuth: false
    isDefault: true
    editable: true

  - name: db01
    type: postgres
    uid: DS_DB_01
    url: db01:5432
    user: postgres
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      database: postgres
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 100 # Grafana v5.4+
      maxIdleConns: 100 # Grafana v5.4+
      maxIdleConnsAuto: true # Grafana v9.5.1+
      connMaxLifetime: 14400 # Grafana v5.4+
      postgresVersion: 1500 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false
