{
 "title": "pgSCV: PostgreSQL",
 "description": "PostgreSQL dashboard for pgSCV metrics (Prometheus version, pgSCV 0.8.0 edition)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(postgres_up,instance)"
    }
   },
   {
    "name": "postgres",
    "query": {
     "query": "label_values(postgres_up,service_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "Current status of PostgreSQL service.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres_up{instance=\"$instance\",service_id=\"$postgres\"}",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Statements",
   "type": "stat",
   "description": "Rate of successfully executed statements per second.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(postgres_statements_calls_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
     "legendFormat": "statements"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Total number of log messages rate (per minute) with severity higher than LOG (e.g. WARNING, ERROR, FATAL and PANIC).",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(postgres_log_messages_total{level!=\"log\",instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Response Time, avg",
   "type": "stat",
   "description": "Average response time calculated using time of executed statements.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(postgres_statements_time_seconds_all_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])) / sum(rate(postgres_statements_calls_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Longest Activity",
   "type": "stat",
   "description": "Current longest transaction activity, initiated by clients or background service (e.g. autovacuum).",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(postgres_activity_max_seconds{instance=\"$instance\",service_id=\"$postgres\"})",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "stat",
   "description": "Total number of connected clients.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(postgres_activity_connections_in_flight{instance=\"$instance\",service_id=\"$postgres\"})",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Client Activity",
     "type": "timeseries",
     "description": "Query activity produced by connected clients.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(postgres_statements_calls_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "statements"
      },
      {
       "expr": "sum(rate(postgres_database_xact_commits_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "commits"
      },
      {
       "expr": "sum(rate(postgres_database_xact_rollbacks_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "rollbacks"
      }
     ]
    },
    {
     "title": "User connections",
     "type": "timeseries",
     "description": "Query activity produced by connected clients.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (user) (postgres_connected_clients_total{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{user}}"
      }
     ]
    },
    {
     "title": "State Client Connections",
     "type": "timeseries",
     "description": "States of connections established by clients (doesn't include states of background services).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (state) (postgres_activity_connections_in_flight{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{state}}"
      },
      {
       "expr": "sum(postgres_activity_connections_in_flight{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "All"
      },
      {
       "expr": "postgres_service_settings_info{name=\"max_connections\", instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "max_connections"
      }
     ]
    },
    {
     "title": "Transactions per second to databases",
     "type": "timeseries",
     "description": "States of connections established by clients (doesn't include states of background services).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "xacts/s" } },
     "targets": [
      {
       "expr": "rate(postgres_database_xact_commits_total{instance=\"$instance\",service_id=\"$postgres\"} +\npostgres_database_xact_rollbacks_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Longest User Activity",
     "type": "timeseries",
     "description": "The most longest activity produced by connected clients and background services.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5, max by (user) (postgres_activity_max_seconds{instance=\"$instance\",service_id=\"$postgres\"}))",
       "legendFormat": "{{user}}"
      }
     ]
    },
    {
     "title": "Session reason end statuses",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (database, reason) (\nincrease(postgres_database_sessions_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "{{database}} / {{reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Log messages, per minute",
     "type": "timeseries",
     "description": "Messages written to log, by severity.",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (level) (increase(postgres_log_messages_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "{{ level }}"
      }
     ]
    },
    {
     "title": "Log directory, bytes",
     "type": "timeseries",
     "description": "Total size of log directory in bytes.",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "postgres_log_directory_bytes{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "{{ path }}"
      }
     ]
    },
    {
     "title": "Logging settings",
     "type": "table",
     "description": "Important: when logging_collector is disabled, log metrics will not be collected.",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (name,setting) (postgres_service_settings_info{instance=\"$instance\",service_id=\"$postgres\",name=~\"logging_collector|log_directory|log_filename\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Statements (pg_stat_statements required)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Calls rate",
     "type": "timeseries",
     "description": "The top-most executed statements.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, (rate(postgres_statements_calls_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])) \n+ on(database,user,queryid) group_left(query) (0 * postgres_statements_query_info{instance=\"$instance\",service_id=\"$postgres\"}))\n\n",
       "legendFormat": "{{database}}/{{user}}/{{query}}"
      }
     ]
    },
    {
     "title": "Rows",
     "type": "timeseries",
     "description": "The top-most statements by returned rows.",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, (rate(postgres_statements_rows_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])) + on(database,user,queryid) group_left(query) (0 * postgres_statements_query_info{instance=\"$instance\",service_id=\"$postgres\"}))",
       "legendFormat": "{{database}}/{{user}}/{{query}}"
      }
     ]
    },
    {
     "title": "Total time",
     "type": "timeseries",
     "description": "The top-most statements by total time (planning, executing and doing IO).",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5, (rate(postgres_statements_time_seconds_all_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])) + on(database,user,queryid) group_left(query) (0 * postgres_statements_query_info{instance=\"$instance\",service_id=\"$postgres\"}))",
       "legendFormat": "{{database}}/{{user}}/{{query}}"
      }
     ]
    },
    {
     "title": "Planing time per second",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk_avg(5,\nsum by (database, queryid, query) (\nrate(postgres_statements_time_seconds_total{instance=\"$instance\",service_id=\"$postgres\",mode=\"planning\"}[1m]) + on(database,user,queryid) group_left(query)\n0 * postgres_statements_query_info{service_id=\"$postgres\"}\n), \"other\")",
       "legendFormat": "{{other}} {{database}} {{queryid}} {{query}}"
      }
     ]
    },
    {
     "title": "Most called queries",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk_avg(5,\nsum by (queryid,query) (\nrate(postgres_statements_calls_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])\n+ on(database,user,queryid) group_left(query)\n0 * postgres_statements_query_info{instance=\"$instance\",service_id=\"$postgres\"}\n), \"other\")\n",
       "legendFormat": "{{other}} {{queryid}} {{query}}"
      }
     ]
    },
    {
     "title": "Queries affecting the most rows",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "rowsps" } },
     "targets": [
      {
       "expr": "topk_avg(5,\nsum by (queryid,query) (\nrate(postgres_statements_rows_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])\n+ on(database,user,queryid) group_left(query)\n0 * postgres_statements_query_info{instance=\"$instance\",service_id=\"$postgres\"}\n), \"other\")",
       "legendFormat": "{{other}} {{queryid}} {{query}}"
      }
     ]
    },
    {
     "title": "IO time",
     "type": "timeseries",
     "description": "The top-most statements by IO time.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5, sum without (mode) (rate(postgres_statements_time_seconds_total{mode=~\"ioread|iowrite\",instance=\"$instance\",service_id=\"$postgres\"}[1m])) + on(database,user,queryid) group_left(query) (0 * postgres_statements_query_info{instance=\"$instance\",service_id=\"$postgres\"}))",
       "legendFormat": "{{database}}/{{user}}/{{query}}"
      }
     ]
    },
    {
     "title": "Functions time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(postgres_function_total_time_seconds_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "{{database}}.{{schema}}.{{function}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Locks and Wait Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Wait Events, by type",
     "type": "timeseries",
     "description": "Wait events aggregated by type.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (type) (postgres_activity_wait_events_in_flight{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "Wait Events",
     "type": "timeseries",
     "description": "The top-most wait events occurred.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, postgres_activity_wait_events_in_flight{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ type }}:{{ event }}"
      }
     ]
    },
    {
     "title": "Locks",
     "type": "timeseries",
     "description": "Total number of locks acquired.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "postgres_locks_in_flight{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "Deadlocks, per minute",
     "type": "timeseries",
     "description": "Total number of deadlocks per minute.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(postgres_database_deadlocks_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "deadlocks"
      }
     ]
    },
    {
     "title": "Maximum waiting time among all processes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "postgres_activity_max_seconds{instance=\"$instance\",service_id=\"$postgres\",state=\"waiting\"}",
       "legendFormat": "deadlocks"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Replication Lag, bytes",
     "type": "timeseries",
     "description": "Total amount of replication lag, when standbys left behind the master.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (client_addr) (postgres_replication_lag_all_bytes{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ client_addr }}"
      }
     ]
    },
    {
     "title": "Replication Lag, seconds",
     "type": "timeseries",
     "description": "Total amount of replication lag, when standbys left behind the master.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (client_addr) (postgres_replication_lag_all_seconds{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ client_addr }}"
      }
     ]
    }
   ]
  },
  {
   "title": "WAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "WAL write, bytes per second",
     "type": "timeseries",
     "description": "Amount of WAL generated or received by Postgres instance.",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(postgres_wal_written_bytes_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "WAL"
      }
     ]
    },
    {
     "title": "WAL directory size",
     "type": "timeseries",
     "description": "Total size of WAL directory, in bytes.",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "postgres_wal_directory_bytes{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "size"
      }
     ]
    },
    {
     "title": "WAL settings",
     "type": "table",
     "description": "WAL settings",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (name,setting) (postgres_service_settings_info{instance=\"$instance\",service_id=\"$postgres\",name=~\"(max|min)_wal_size|max_slot_wal_keep_size|full_page_writes|wal_keep_(size|segments)|wal_(compression|level|log_hints)\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Vacuum Maintenance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Vacuums",
     "type": "timeseries",
     "description": "Total number of automatic and user-initiated vacuum operations.",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "postgres_activity_vacuums_in_flight{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Vacuumed tables, per-minute",
     "type": "timeseries",
     "description": "The top-most vacuumed tables.",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, increase(postgres_table_maintenance_total{type=\"autovacuum\",instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "{{ table }}"
      }
     ]
    },
    {
     "title": "Autovacuum settings",
     "type": "table",
     "description": "Autovacuum settings.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (name,setting) (postgres_service_settings_info{instance=\"$instance\",service_id=\"$postgres\",name=~\"^(auto)?vacuum.+\"})"
      }
     ]
    },
    {
     "title": "Transactions left before wraparound",
     "type": "graph",
     "description": "Total number transactions left before XID wraparound occurs.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "postgres_xacts_left_before_wraparound{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "{{ xid_from }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Background Writes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Checkpoints",
     "type": "timeseries",
     "description": "Total number of checkpoints occurred.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(postgres_checkpoints_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "{{ checkpoint }}"
      }
     ]
    },
    {
     "title": "Background Writes",
     "type": "timeseries",
     "description": "Total writes performed by background services or by backends implicitly.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(postgres_written_bytes_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "{{ process }}"
      },
      {
       "expr": "rate(postgres_wal_written_bytes_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "wal"
      },
      {
       "expr": "sum(rate(postgres_database_temp_bytes_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "tempfiles"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Tables",
     "type": "timeseries",
     "description": "Top tables by size in bytes.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(30, postgres_table_size_bytes{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ database }}.{{ schema }}.{{ table }}"
      }
     ]
    },
    {
     "title": "Indexes",
     "type": "timeseries",
     "description": "Top indexes by size in bytes.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(30, postgres_index_size_bytes{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ database }}.{{ schema }}.{{ table }}.{{ index }}"
      }
     ]
    },
    {
     "title": "Databases",
     "type": "timeseries",
     "description": "Top databases by size.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(5, postgres_database_size_bytes{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ database }}"
      }
     ]
    },
    {
     "title": "Temporary Files in-flight",
     "type": "timeseries",
     "description": "Total size of active temporary files in-flight.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "postgres_temp_bytes_in_flight{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "{{ tablespace }}"
      }
     ]
    },
    {
     "title": "Databases Temporary Files",
     "type": "timeseries",
     "description": "Top databases by produced temporary files in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(5, increase(postgres_database_temp_bytes_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "{{ database }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Sequential Read, by rows",
     "type": "timeseries",
     "description": "The top-most tables which accessed sequentially.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "tup/s" } },
     "targets": [
      {
       "expr": "topk(5, rate(postgres_table_seq_tup_read_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "{{database}}.{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "Dead Tuples",
     "type": "timeseries",
     "description": "The top-most tables with dead tuples.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, postgres_table_tuples_dead_total{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{database}}.{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "INSERTs",
     "type": "timeseries",
     "description": "The top-most tables with performed INSERTs per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "tup/s" } },
     "targets": [
      {
       "expr": "topk(5, rate(postgres_table_tuples_inserted_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "{{database}}.{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "UPDATEs",
     "type": "timeseries",
     "description": "The top-most tables with performed UPDATEs (including HOT) per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "tup/s" } },
     "targets": [
      {
       "expr": "topk(5, rate(postgres_table_tuples_updated_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "{{database}}.{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "DELETEs",
     "type": "timeseries",
     "description": "The top-most tables with performed DELETEs per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, rate(postgres_table_tuples_deleted_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "{{database}}.{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "Tuples",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "tup/s" } },
     "targets": [
      {
       "expr": "sum(rate(postgres_database_tuples_fetched_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "fetched"
      },
      {
       "expr": "sum(rate(postgres_database_tuples_returned_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "returned"
      },
      {
       "expr": "sum(rate(postgres_database_tuples_inserted_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "inserted"
      },
      {
       "expr": "sum(rate(postgres_database_tuples_updated_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "updated"
      },
      {
       "expr": "sum(rate(postgres_database_tuples_deleted_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "deleted"
      }
     ]
    }
   ]
  },
  {
   "title": "WAL Archiving",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "WAL Archiving Lag, bytes",
     "type": "timeseries",
     "description": "Total amount of WAL segments (in bytes) which are not archived yet.",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "postgres_archiver_lag_bytes{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "bytes"
      }
     ]
    },
    {
     "title": "WAL Archiving, per minute",
     "type": "timeseries",
     "description": "Total amount of WAL segments processed per minute.",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(postgres_archiver_archived_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "archived"
      },
      {
       "expr": "increase(postgres_archiver_failed_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "failed"
      }
     ]
    },
    {
     "title": "WAL archiving settings",
     "type": "table",
     "description": "Important: when WAL archiving is disabled, metrics will not be collected.",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (name,setting) (postgres_service_settings_info{instance=\"$instance\",service_id=\"$postgres\",name=~\"archive_.+\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory and IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Shared buffers usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "Mib" } },
     "targets": [
      {
       "expr": "postgres_shared_buffers_all_usage_bytes{instance=\"$instance\", service_id=\"$postgres\"}/1024/1024",
       "legendFormat": "{{buffers}}"
      }
     ]
    },
    {
     "title": "Table read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "blocks/s" } },
     "targets": [
      {
       "expr": "sum by (database, schema, table)\n(rate(postgres_table_io_blocks_total{instance=\"$instance\", service_id=\"$postgres\",access=\"read\"}[1m]))",
       "legendFormat": "{{database}}.{{schema}}.{{table}}"
      }
     ]
    }
   ]
  }
 ]
}